spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: banu
    url: jdbc:postgresql://localhost:5432/employee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: codabanulab@gmail.com
    password: banu3195@321
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 1MB
server:
   port: 8080
   
upload:
  dir:
    location:
      /resources/image